import {
  GraduationCap,
  Monitor,
  Award,
  Server,
  Database,
  Shield,
  Container,
  Rocket,
  Brain,
  User,
  Lightbulb,
  Palette,
  Target,
  Briefcase,
  Mail,
  GithubIcon,
  LinkedinIcon,
  MapPin,
  Heart,
  MessageCircle,
  Users,
  Clock,
  RefreshCw,
  Puzzle,
  type LucideIcon,
} from 'lucide-react';

export const iconMap: Record<string, LucideIcon> = {
  'graduation-cap': GraduationCap,
  monitor: Monitor,
  award: Award,
  server: Server,
  database: Database,
  shield: Shield,
  container: Container,
  rocket: Rocket,
  brain: Brain,
  user: User,
  lightbulb: Lightbulb,
  palette: Palette,
  target: Target,
  briefcase: Briefcase,
  mail: Mail,
  github: GithubIcon,
  linkedin: LinkedinIcon,
  'map-pin': MapPin,
  heart: Heart,
  'message-circle': MessageCircle,
  users: Users,
  clock: Clock,
  'refresh-cw': RefreshCw,
  puzzle: Puzzle,
};
